### ISSUE TITLE
Implement Initiative

### ISSUE THREAD

**Issue by ScottMaclure** [Futil/foundry-mothership#1]
Hi there, thanks for making MoSh.

Does initiative need to be implemented? I tried today and it seems to sort by highest 1d100 roll.

> Section 9.2
> First: you and your crew mates each make a Speed Check; those who pass can act before the enemies. Those who Fail act after.

(Can handle crit success + failure outside of initaitive, but would be nice to have a visual indicator or something)

Thoughts?

**Comment by hollowphoton** [comment]
![image](https://github.com/Futil/foundry-mothership/assets/17795348/6e763d51-78dd-4710-b70d-8e1ca6f7ea88)

The final 1e PDF now has a very simplified turn order that goes between Warden and the players, rather than specifying a specific turn order per player character. As a result, we are not pursuing the implementation of initiative within this system. This may change with future updates to Mothership, but for now we are marking this ticket as resolved.
